ECommerceLiteUI/Controllers/PartialsController.cs
using ECommerceLiteBLL.Account;
using ECommerceLiteBLL.Repository;
using ECommerceLiteEntity.IdentityModels;
using ECommerceLiteUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ECommerceLiteUI.Controllers
{
    public class PartialsController : BaseController
    {
        //Global Alan

        CategoryRepo myCategoryRepo = new CategoryRepo();
        ProductRepo myProductRepo = new ProductRepo();

        private object MemberShipTools;

        public PartialViewResult AdminSideBarResult()
        {
            //TODO: name surname alınacak
            TempData["NameSurname"] = "";
            return PartialView("_PartialAdminSideBar");
        }
        public PartialViewResult AdminSideBarMenuResult()
        {

            return PartialView("_PartialAdminSideBarMenu");
        }

        public PartialViewResult UserNameSurnameOnHomePage()
        {
            if (HttpContext.User.Identity.IsAuthenticated)
            {
                var loggedInUser = MembershipTools.GetUser();
                return PartialView("_PartialUserNameSurnameOnHomePage", loggedInUser);
                
            }
            return PartialView("_PartialUserNameSurnameOnHomePage",null);
        }

        public PartialViewResult ShoppingCart()
        {
            var shoppingCart = Session["ShoppingCart"] as List<CartViewModel>;
            if (shoppingCart==null)
            {
                return PartialView("_PartialShoppingCart", new List<CartViewModel>());

            }
            else
            {
                return PartialView("_PartialShoppingCart", shoppingCart);

            }
        }

        public PartialViewResult AdminSideBarCategories()
        {
            //controller arasında veri taşımaya yarar Actiondan sayfaya veri taşıma
            TempData["AllCategoriesCount"] = myCategoryRepo.Queryable().Where(x => x.BaseCategory == null).ToList().Count;
            return PartialView("_PartialAdminSideBarCategories");
        }

        public PartialViewResult AdminSideBarProducts()
        {
            TempData["CategoryProductsCount"] = myProductRepo.GetAll().Count;
            return PartialView("_PartialAdminSideBarProducts");
        } 

    }
}

ECommerceLiteUI/Views/Shared/View.cshtml
@{
    ViewBag.Title = "View";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

ECommerceLiteUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

ECommerceLiteUI/Views/Shared/_LayoutAdmin.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>ECommerceLite Admin Panel</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/AdminLTE/plugins/fontawesome-free/css/all.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Tempusdominus Bbootstrap 4 -->
    <link rel="stylesheet" href="~/AdminLTE/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">
    <!-- iCheck -->
    <link rel="stylesheet" href="~/AdminLTE/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- JQVMap -->
    <link rel="stylesheet" href="~/AdminLTE/plugins/jqvmap/jqvmap.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/AdminLTE/dist/css/adminlte.min.css">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="~/AdminLTE/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
    <!-- Daterange picker -->
    <link rel="stylesheet" href="~/AdminLTE/plugins/daterangepicker/daterangepicker.css">
    <!-- summernote -->
    <link rel="stylesheet" href="~/AdminLTE/plugins/summernote/summernote-bs4.css">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<body class="hold-transition sidebar-mini layout-fixed">
    <div class="wrapper">

        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand navbar-white navbar-light">
            <!-- Left navbar links -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
                </li>
                <li class="nav-item d-none d-sm-inline-block">
                    <a href="index3.html" class="nav-link">Anasayfa</a>
                </li>

            </ul>


        </nav>
        <!-- /.navbar -->
        <!-- Main Sidebar Container -->
        <aside class="main-sidebar sidebar-dark-primary elevation-4">
            <!-- Brand Logo -->
            <a href="Home/Index" class="brand-link">

                <img src="~/AdminLTE/dist/img/103.png" alt="AdminLTE Logo"
                     class="brand-image img-circle elevation-3" style="opacity: .8" />

                <span class="brand-text font-weight-light">Electro Admin Panel</span>
            </a>

            <!-- Sidebar -->
            <div class="sidebar">
                @{
                    Html.RenderAction("AdminSideBarResult", "Partials");
                }
                @{
                    Html.RenderAction("AdminSideBarMenuResult", "Partials");

                }
            </div>
            <!-- /.sidebar -->

        </aside>


        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <div class="content-header">
                <div class="container-fluid">
                    <div class="row mb-2">
                        <div class="col-12">
                            @RenderBody()
                        </div><!-- /.col -->
                    </div><!-- /.row -->
                </div><!-- /.container-fluid -->
            </div>

        </div>
        <!-- /.content-wrapper -->
        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
            <!-- Control sidebar content goes here -->
        </aside>
        <!-- /.control-sidebar -->
    </div>
    <!-- ./wrapper -->
    <!-- jQuery -->
    <script src="~/AdminLTE/plugins/jquery/jquery.min.js"></script>
    <!-- jQuery UI 1.11.4 -->
    <script src="~/AdminLTE/plugins/jquery-ui/jquery-ui.min.js"></script>
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>$.widget.bridge('uibutton', $.ui.button)</script>
    <!-- Bootstrap 4 -->
    <script src="~/AdminLTE/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- ChartJS -->
    <script src="~/AdminLTE/plugins/chart.js/Chart.min.js"></script>
    <!-- Sparkline -->
    <script src="~/AdminLTE/plugins/sparklines/sparkline.js"></script>
    <!-- JQVMap -->
    <script src="~/AdminLTE/plugins/jqvmap/jquery.vmap.min.js"></script>
    <script src="~/AdminLTE/plugins/jqvmap/maps/jquery.vmap.usa.js"></script>
    <!-- jQuery Knob Chart -->
    <script src="~/AdminLTE/plugins/jquery-knob/jquery.knob.min.js"></script>
    <!-- daterangepicker -->
    <script src="~/AdminLTE/plugins/moment/moment.min.js"></script>
    <script src="~/AdminLTE/plugins/daterangepicker/daterangepicker.js"></script>
    <!-- Tempusdominus Bootstrap 4 -->
    <script src="~/AdminLTE/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"></script>
    <!-- Summernote -->
    <script src="~/AdminLTE/plugins/summernote/summernote-bs4.min.js"></script>
    <!-- overlayScrollbars -->
    <script src="~/AdminLTE/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/AdminLTE/dist/js/adminlte.js"></script>
    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
    <script src="~/AdminLTE/dist/js/pages/dashboard.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="~/AdminLTE/dist/js/demo.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

ECommerceLiteUI/Views/Shared/_LayoutUser.cshtml
@using ECommerceLiteBLL.Account
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="tr">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <title>ECommerceLite Project</title>

    <!-- Google font -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,500,700" rel="stylesheet">

    <!-- Bootstrap -->
    <link href="~/Electro-Theme/css/bootstrap.min.css" rel="stylesheet" />

    <!-- Slick -->
    <link type="text/css" rel="stylesheet" href="~/Electro-Theme/css/slick.css" />
    <link type="text/css" rel="stylesheet" href="~/Electro-Theme/css/slick-theme.css" />

    <!-- nouislider -->
    <link type="text/css" rel="stylesheet" href="~/Electro-Theme/css/nouislider.min.css" />

    <!-- Font Awesome Icon -->
    <link rel="stylesheet" href="~/Electro-Theme/css/font-awesome.min.css">

    <!-- Custom stlylesheet -->
    <link type="text/css" rel="stylesheet" href="~/Electro-Theme/css/style.css" />

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>
<body>
    <!-- HEADER -->
    <header>
        <!-- TOP HEADER -->
        <div id="top-header">
            <div class="container">
                <ul class="header-links pull-left">
                    <li><a href="#"><i class="fa fa-mobile-phone"></i> +9 0507 320 0699</a></li>
                    <li><a href="#"><i class="fa fa-envelope-o"></i> seydaazenler@gmail.com</a></li>
                    <li><a href="#"><i class="fa fa-map-marker"></i> istanbul, TÜRKİYE </a></li>
                </ul>
                <ul class="header-links pull-right">
                    @{ 
                        Html.RenderAction("UserNameSurnameOnHomePage", "Partials");
                    }



                    @if (MembershipTools.GetUser() != null)
                    {

                        <li><a href="/Account/Logout"><i class="fa fa-sign-out"></i>Çıkış Yap</a></li>

                    }
                    else
                    {
                        <li><a href="/Account/Login"><i class="fa fa-sign-out"></i>Giriş Yap</a></li>
                    }
                </ul>
            </div>
        </div>
        <!-- /TOP HEADER -->
        <!-- MAIN HEADER -->
        <div id="header">
            <!-- container -->
            <div class="container">
                <!-- row -->
                <div class="row">
                    <!-- LOGO -->
                    <div class="col-md-3">
                        <div class="header-logo">
                            <a href="/Home/Index" class="logo">
                                <img src="~/Electro-Theme/img/103logo.png" alt="">
                                
                            </a>
                        </div>
                    </div>
                    <!-- /LOGO -->
                    <!-- SEARCH BAR -->
                    <div class="col-md-5">
                        <div class="header-search">
                            <form>
                                <select class="input-select">
                                    <option value="0">Tümü</option>
                                    <option value="1">Yeni Gelenler</option>
                                    <option value="1">Çok Satanlar</option>
                                </select>
                                <input class="input" placeholder="Ara..">
                                <button class="search-btn">Ara</button>
                            </form>
                        </div>
                    </div>
                    <!-- /SEARCH BAR -->
                    <!-- ACCOUNT -->
                    <div class="col-md-4 clearfix">
                        <div class="header-ctn">
                            <!--Order-->
                            <div>
                                <a href="/Home/Order">
                                    <i class="fa fa-shopping-basket"></i>
                                    <span>Siparişlerim</span>
                                </a>
                            </div>
                            <!--/Order-->
                            <!-- Wishlist -->
                            <div>
                                <a href="#">
                                    <i class="fa fa-heart-o"></i>
                                    <span>Favorilerim</span>
                                    <div class="qty">2</div>
                                </a>
                            </div>
                            <!-- /Wishlist -->
                            <!-- Cart -->
                            @{
                                Html.RenderAction("ShoppingCart", "Partials");
                            }
                            <!-- /Cart -->
                            <!-- Menu Toogle -->
                            <div class="menu-toggle">
                                <a href="#">
                                    <i class="fa fa-bars"></i>
                                    <span>Menü</span>
                                </a>
                            </div>
                            <!-- /Menu Toogle -->
                        </div>
                    </div>
                    <!-- /ACCOUNT -->
                </div>
                <!-- row -->
            </div>
            <!-- container -->
        </div>
        <!-- /MAIN HEADER -->
    </header>
    <!-- /HEADER -->
    <!-- SECTION -->
    <div class="section">
        <!-- container -->
        <div class="container">
            <!-- row -->
            <div class="row">
                @RenderBody()
            </div>
            <!-- /row -->
        </div>
        <!-- /container -->
    </div>
    <!-- /SECTION -->
    <!-- FOOTER -->
    <footer id="footer">
        <!-- top footer -->
        <div class="section">
            <!-- container -->
            <div class="container">
                <!-- row -->
                <div class="row">
                    <div class="col-md-3 col-xs-6">
                        <div class="footer">
                            <h3 class="footer-title">Hakkımızda</h3>
                            <p>Güvenli Alışveriş, Uygun Fiyatlı ihtiyacınız olan tüm elektronik ürünler Electro'da!</p>
                            <ul class="footer-links">
                                <li><a href="#"><i class="fa fa-map-marker"></i>istanbul,TÜRKİYE</a></li>
                                <li><a href="#"><i class="fa fa-phone"></i>+90 507 320 0699</a></li>
                                <li><a href="#"><i class="fa fa-envelope-o"></i>seydaazenler@gmail.com</a></li>
                            </ul>
                        </div>
                    </div>

                    <div class="col-md-3 col-xs-6">
                        <div class="footer">
                            <h3 class="footer-title">Kategoriler</h3>
                            <ul class="footer-links">
                                <li><a href="#">Elektronik</a></li>
                                <li><a href="#">Küçük Ev Aletleri</a></li>
                                <li><a href="#">Oyun-Hobi</a></li>
                                <li><a href="#">Bilgisayar-Laptop</a></li>
                                
                            </ul>
                        </div>
                    </div>

                    <div class="clearfix visible-xs"></div>

                    <div class="col-md-3 col-xs-6">
                        <div class="footer">
                            <h3 class="footer-title">Kurumsal</h3>
                            <ul class="footer-links">
                                <li><a href="#">Hakkımızda</a></li>
                                <li><a href="#">İletişim</a></li>
                                <li><a href="#">Gizlilik Politikası</a></li>
                                <li><a href="#">KVKK</a></li>
                            </ul>
                        </div>
                    </div>

                    <div class="col-md-3 col-xs-6">
                        <div class="footer">
                            <h3 class="footer-title">HESABIM</h3>
                            <ul class="footer-links">
                                <li><a href="#">Hesabım</a></li>
                                <li><a href="#">Sepetim</a></li>
                                <li><a href="#">Favorilerim</a></li>
                                <li><a href="#">Siparişlerim</a></li>
                                <li><a href="#">Destek</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <!-- /row -->
            </div>
            <!-- /container -->
        </div>
        <!-- /top footer -->
        <!-- bottom footer -->
        <div id="bottom-footer" class="section">
            <div class="container">
                <!-- row -->
                <div class="row">
                    <div class="col-md-12 text-center">
                        <ul class="footer-payments">
                            <li><a href="#"><i class="fa fa-cc-visa"></i></a></li>
                            <li><a href="#"><i class="fa fa-credit-card"></i></a></li>
                            <li><a href="#"><i class="fa fa-cc-paypal"></i></a></li>
                            <li><a href="#"><i class="fa fa-cc-mastercard"></i></a></li>
                            <li><a href="#"><i class="fa fa-cc-discover"></i></a></li>
                            <li><a href="#"><i class="fa fa-cc-amex"></i></a></li>
                        </ul>
                        <span class="copyright">
                            <a target="_blank" href="https://www.templateshub.net">2022 Network Academy</a>
                        </span>


                    </div>
                </div>
                <!-- /row -->
            </div>
            <!-- /container -->
        </div>
        <!-- /bottom footer -->
    </footer>
    <!-- /FOOTER -->
    <!-- jQuery Plugins -->
    <script src="~/Electro-Theme/js/jquery.min.js"></script>
    <script src="~/Electro-Theme/js/bootstrap.min.js"></script>
    <script src="~/Electro-Theme/js/slick.min.js"></script>
    <script src="~/Electro-Theme/js/nouislider.min.js"></script>
    <script src="~/Electro-Theme/js/jquery.zoom.min.js"></script>
    <script src="~/Electro-Theme/js/main.js"></script>


</body>
@RenderSection("scripts", required: false)
</html>

ECommerceLiteUI/Views/Shared/_PartialAdminSideBar.cshtml
 <!-- Sidebar user panel (optional) -->
    <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
            <img src="~/AdminLTE/dist/img/avatar2.png" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
            <a href="#" class="d-block">@TempData["NameSurname"]</a>
        </div>
    </div>

ECommerceLiteUI/Views/Shared/_PartialAdminSideBarCategories.cshtml
<li class="nav-item">
    <a href="/Category/CategoryList" class="nav-link">
        <i class="nav-icon fas fa-th"></i>
        <p>
            Kategoriler
            <span class="right badge badge-danger">@TempData["AllCategoriesCount"]</span>
        </p>
    </a>
</li>

ECommerceLiteUI/Views/Shared/_PartialAdminSideBarMenu.cshtml
                <!-- Sidebar Menu -->
<nav class="mt-2">
    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
        <!-- Add icons to the links using the .nav-icon class
             with font-awesome or any other icon font library -->
        <li class="nav-item has-treeview menu-open">
            <a href="/Admin/Dashboard" class="nav-link active">
                <i class="nav-icon fas fa-tachometer-alt"></i>
                <p>
                    Dashboard
                    <i class="right fas fa-angle-left"></i>
                </p>
            </a>
        </li>
        @{
            Html.RenderAction("AdminSideBarCategories", "Partials");
        }
        @{
            Html.RenderAction("AdminSideBarProducts", "Partials");
        }
        <li class="nav-item has-treeview">
            <a href="#" class="nav-link">
                <i class="nav-icon fas fa-chart-pie"></i>
                <p>
                    Müşteriler
                    <i class="right fas fa-angle-left"></i>
                </p>
            </a>
            <ul class="nav nav-treeview">
                <li class="nav-item">
                    <a href="pages/charts/chartjs.html" class="nav-link">
                        <i class="far fa-circle nav-icon"></i>
                        <p>ChartJS</p>
                    </a>
                </li>
            </ul>
        </li>


    </ul>
</nav>
<!-- /.sidebar-menu -->

ECommerceLiteUI/Views/Shared/_PartialAdminSideBarProducts.cshtml
<li class="nav-item has-treeview">
    <a href="/Product/ProductList" class="nav-link">
        <i class="nav-icon fas fa-copy"></i>
        <p>
            Ürünler
            <i class="fas fa-angle-left right"></i>
        </p>
    </a>
    <ul class="nav nav-treeview">
        <li class="nav-item">
            <a href="/Product/ProductList" class="nav-link">
                <i class="far fa-circle nav-icon"></i>
                <p>
                    Tüm Ürünler
                </p>
            </a>
        </li>
    </ul>

    <ul class="nav nav-treeview">
        <li class="nav-item">
            <a href="/Product/CategoryProducts" class="nav-link">
                <i class="far fa-circle nav-icon"></i>
                <p>
                    Kategoriye Göre
                    <span class="badge badge-info right">@TempData["CategoryProductsCount"]</span>
                </p>
            </a>
        </li>
    </ul>
    <ul class="nav nav-treeview">
        <li class="nav-item">
            <a href="/Product/ProductList?isNew=true" class="nav-link">
                <i class="far fa-circle nav-icon"></i>
                <p>Yeni Ürünler</p>
            </a>
        </li>
    </ul>
</li>

ECommerceLiteUI/Views/Shared/_PartialShoppingCart.cshtml
@using ECommerceLiteUI.Models
@model List<CartViewModel>
<div class="dropdown">
    <a class="dropdown-toggle" data-toggle="dropdown" aria-expanded="true">
        <i class="fa fa-shopping-cart"></i>
        <span>Sepetim</span>
        <div class="qty">@Model.Count.ToString()</div>
    </a>
    <div class="cart-dropdown">
        <div class="cart-list">

            @foreach (var item in Model)
            {
                <div class="product-widget">
                    @*<div class="product-img">
                        <img src="./img/product01.png" alt="">
                    </div>*@
                    <div class="product-body">
                        <h3 class="product-name"><a href="/Home/ProductDetail/@item.Id">@item.ProductName</a></h3>
                        <h4 class="product-price"><span class="qty">@item.Quantity x </span>@item.Price ₺</h4>
                    </div>
                    <button class="delete"><i class="fa fa-close"></i></button>
                </div>

            }

        </div>
        @{ decimal total =
                    Model.Sum(x => x.Price) == 0 ? 0 : Model.Sum(x => (x.Quantity * x.Price));
        }
        <div class="cart-summary">
            <small>Sepetinizde @Model.Sum(x => x.Quantity).ToString() adet ürün mevcuttur. </small>
            <h5>Toplam: $2940.00</h5>
        </div>
        <div class="cart-btns">
            <a href="/Home/Cart">Sepete Git</a>
            <a href="/Home/Buy">Alışverişi Tamamla<i class="fa fa-arrow-circle-right"></i></a>
        </div>
    </div>
</div>

ECommerceLiteUI/Views/Shared/_PartialUserNameSurnameOnHomePage.cshtml
@using ECommerceLiteEntity.IdentityModels
@model ApplicationUser
@if (Model != null)
{
    <li>
        <div class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user-o"></i>@Model.Name @Model.Surname</a>

            <ul class="dropdown-menu" style="background-color:#15161d;">
                <li><a href="/Account/UserProfile" style="color: #d10024; font-weight: bold;"><i class="fa fa-user-o"></i>Hesap Bilgileri</a></li>
                <li><a href="/Home/Order" style="color: #d10024; font-weight: bold;"><i class="fa fa-shopping-cart"></i>Siparişlerim</a></li>
            </ul>
        </div>
    </li>
    
}
else
{
    <li><a href="/Account/UserProfile"><i class="fa fa-user-o"></i>HESABIM</a></li>
}